/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        
        //simple driver that just tests two example array with no user input
        int[] nums = {44, -13, 5, 1, 9, -3, 7, 8, 10, 24, -77, 115};

        LoopStats loopStats = new LoopStats();
        StreamStats streamStats = new StreamStats();

        
        //Loop Test 1
        System.out.println("\n\n-------------------------------");
        System.out.println("Test 1");
        System.out.println("Array contents: " + Arrays.toString(nums));
        System.out.println("Loop Functions:");
        System.out.println("Maximum: " + loopStats.maximum(nums));
        System.out.println("Minimum: " + loopStats.minimum(nums));
        System.out.println("Sum: " + loopStats.sum(nums));
        System.out.println("Average: " + loopStats.average(nums));

        //not sure why println does not work for this ones
        loopStats.printOddNumbers(nums);
        loopStats.printEvenNumbers(nums);

        //Stream Test 1
        System.out.println("\nStream Functions");
        System.out.println("Maximum: " + streamStats.maximum(nums));
        System.out.println("Minimum: " + streamStats.minimum(nums));
        System.out.println("Sum: " + streamStats.sum(nums));
        System.out.println("Average: " + streamStats.average(nums));
        streamStats.printOddNumbers(nums);
        streamStats.printEvenNumbers(nums);


        int[] nums2 = {44, -18, 117, -1000, -55, -14, 1, 19, 22, 44, 181, 11, 35, 99, 1741, -5741 };

        //Loop Test 2
        System.out.println("\n\n-------------------------------");
        System.out.println("\nTest 2");
        System.out.println("Array contents: " + Arrays.toString(nums2));
        System.out.println("Loop Functions:");
        System.out.println("Maximum: " + loopStats.maximum(nums2));
        System.out.println("Minimum: " + loopStats.minimum(nums2));
        System.out.println("Sum: " + loopStats.sum(nums2));
        System.out.println("Average: " + loopStats.average(nums2));
        loopStats.printOddNumbers(nums2);
        loopStats.printEvenNumbers(nums2);

        //Stream Test 1
        System.out.println("\nStream Functions");
        System.out.println("Maximum: " + streamStats.maximum(nums2));
        System.out.println("Minimum: " + streamStats.minimum(nums2));
        System.out.println("Sum: " + streamStats.sum(nums2));
        System.out.println("Average: " + streamStats.average(nums2));

        //not sure why println does not work for this ones
        streamStats.printOddNumbers(nums2);
        streamStats.printEvenNumbers(nums2);
        System.out.println("\n\n-------------------------------");
    }
}
