/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void testMainRuns() {
        // Blank test for app.java
        String[] args = {};
        assertDoesNotThrow(() -> App.main(args));
    }

}
