/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import  java.io.ByteArrayOutputStream;
import  java.io.PrintStream;

import  org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class LoopStatsTest {

    private LoopStats loopStats;
    private int[] nums;

    private  final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    private  final PrintStream originalOut = System.out;

    @BeforeEach
    void setUp() {
        loopStats = new  LoopStats();
        nums = new int[]{5, 1, 9, -3, 7, 8, 10}; 
        System.setOut(new PrintStream(outputStream));
    }
    //simple test for each function no real input control since there is none
    @AfterEach
    void  restoreStreams() {
          System.setOut(originalOut);
    }
    
    @Test
    void testMaximum() {
        assertEquals(10,  loopStats.maximum(nums));
    }

    @Test
    void testMinimum() {
        assertEquals(-3,  loopStats.minimum(nums));
    }

    @Test
    void testSum() {
        assertEquals(37,  loopStats.sum(nums));
    }
 
    @Test
    void testAverage() {
        assertEquals(37.0 / 7,    loopStats.average(nums));
    }

    @Test
    void testPrintOddNumbers() {
        loopStats.printOddNumbers(nums);
        String output =    outputStream.toString().trim();
        assertTrue(output.contains("5 1 9 -3 7" ),   "Odd numbers output incorrect");
    }

    @Test
    void testPrintEvenNumbers() {
        loopStats.printEvenNumbers(nums);
        String output =    outputStream.toString().trim();
        assertTrue(output.contains("8 10" ),   "Even numbers output incorrect");
    }

}
