/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;



import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class StreamStatsTest {

    private StreamStats streamStats;
    private int[] nums;

    private final  ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    private final  PrintStream originalOut = System.out;

    @BeforeEach
    void setUp() {
        streamStats = new StreamStats();
        nums = new int[]{5, 1, 9, -3, 7, 8, 10};
        System.setOut(new PrintStream(outputStream));
    }
//simple test for each function no real input control since there is none
    @AfterEach
    void restoreStreams() {
        System.setOut(originalOut);
    }

    @Test
    void testMaximum() {
         assertEquals(10, streamStats.maximum(nums));
    }

    @Test
     void testMinimum() {
        assertEquals(-3, streamStats.minimum(nums));
    }

    @Test
    void testSum() {
        assertEquals(37, streamStats.sum(nums));
    }
  
    @Test
    void testAverage() {
        assertEquals(37.0 / 7, streamStats.average(nums));
    }

    @Test
    void testPrintOddNumbers() {
        streamStats.printOddNumbers(nums);
        String output = outputStream.toString().trim();
         assertTrue(output.contains("5 1 9 -3 7"), "Odd numbers output incorrect");
    }

    @Test
    void testPrintEvenNumbers() {
        streamStats.printEvenNumbers(nums);
        String output = outputStream.toString().trim();
         assertTrue(output.contains("8 10"), "Even numbers output incorrect");
    } 

     
}
